[RSpec編] 04_未完成のテストコード修正
asm181818/rspec_app_exam pull request #1
Opened 2020-06-19 05:32 UTC by asm181818

#TODO
テストケース内で指示された箇所のローカル変数で定義されたFactoryBotのテストデータをdescribe単位でletで定義
it '既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと' 内のtaskのテストデータに関しては、traitを使用してstatusとcompletion_dateを含むcompletion_taskを作成

#FIXME
①テストケース it 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること'
click_link 'View Todos'以下でproject詳細画面の検証がされ、テストが失敗する状況だったため、 'View Todos'をクリックして別タブで開かれるタスク一覧ページが検証の対象となるようにswitch_to_window(windows.last)を追記
②テストケース it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること' 
編集後のタスクの日時形式がテストに引っかかっていたため、テスト側の日時の表示形式を修正
③テストケース it 'Taskが削除されること'
Destroyリンクをクリック後のページで検証する文字列を、削除成功のフラッシュメッセージに変更

2020-06-19 06:20 UTC, yuji91 requested changes

2020-06-19 06:20 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { 'done' }
enumの値はStringではなくSymbolの形式で記載した方が良いですね！
```suggestion
      status { :done }
```

2020-06-19 06:20 UTC, yuji91 commented on spec/factories/tasks.rb
> +    project_id { 1 }
idを指定しているのは`belongs_to`のオプションによる必須項目のためでしょうか？
そうであれば、idの指定ではなく関連するデータを作成する形にしましょう！
```suggestion
    association :project
```

2020-06-19 06:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +    let(:task) { FactoryBot.create(:task) }
今回のテストケースでは、projectは1度のみ作成すれば十分なのでtaskのデータ作成時に併せて作成させるようにしましょう！

また、FactoryBotの指定は省略するのが良いです。
```suggestion
    let(:task) { create(:task) }
```

2020-06-19 06:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %-H:%M'))
こちら解答例前編（NG例）でも指摘がありますが、表示時刻については、view側で使用しているメソッドを呼び出す形にしましょう。

実装側の時刻表示の仕様が変わってもテストが失敗しないようにしたいです。
https://github.com/runtequn/rspec_app_exam/pull/1

2020-06-19 06:20 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content 'Task was successfully destroyed.'
こちらは「`task.title`を指定するとテストが落ちてしまう」という暗黙知ができてしまうので、テスト対象の画面をブラウザの検証ツールで開いて、どう修正するべきかを考えてみてください。

2020-06-20 10:19 UTC, yuji91 requested changes

2020-06-20 10:19 UTC, yuji91 commented on spec/system/task_spec.rb
> +include ApplicationHelper
ファイル個別にincludeしなくても、設定ファイル自体に読み込ませると全体で使えるようになります！

2020-06-20 10:19 UTC, yuji91 commented on spec/factories/tasks.rb
> +    association :project
Factoryの`associtation`は一番上ではなくtraitの定義の上に記載するのが一般的な気がします！

ちなみにこの`associtation`の記載は省略が可能です。

2020-06-22 13:38 UTC, asm181818 commented on spec/system/task_spec.rb
> +include ApplicationHelper
f51d97b で修正しました

2020-06-22 13:38 UTC, asm181818 commented on spec/factories/tasks.rb
> +    association :project
2167a09 で修正しました

2020-06-23 02:04 UTC, yuji91 approved these changes

2020-06-23 16:31 UTC, merged

2022-07-12 02:46 UTC, fushimi35 commented on spec/factories/tasks.rb
> +    project_id { 1 }
07b8f8f にて修正しました。